[phases.build]
packages = ["python39", "gcc"]
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "/opt/venv/bin/pip3 install --upgrade pip setuptools",
    "/opt/venv/bin/pip3 install flask pandas==1.3.3",
d]

[phases.install]
commands = [
    "/opt/venv/bin/pip3 install -r requirements.txt"
]