[build]
packages = ["python39", "gcc"]

[phases.setup]
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "/opt/venv/bin/pip install flask pandas",
    "/opt/venv/bin/pip install pandas",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.install]
commands = [
    "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.start]
commands = [
    ". /opt/venv/bin/activate",
    "python3 app.py"
]
