[build]
packages = ["python39", "gcc"]

[phases.setup]
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "/opt/venv/bin/pip3 install --upgrade pip3 setuptools",
    "/opt/venv/bin/pip3 install flask pandas==1.3.3",
]
