[build]
packages = ["python39", "gcc"]

[phases.setup]
commands = [
    "python3 -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip3 install flask",
    "pip3 install pandas",
    "pip3 install -r requirements.txt"
]

[phases.install]
commands = [
    "pip3 install -r requirements.txt"
]

[phases.start]
commands = [
    "python3 app.py"
]